-- Table to create destination type
-- examples:  SIP Phone, Skype, Google Voice, Starphone
-- This SQL script both creates the table and populate it.
-- For a more complicated table the add and insert scripts should be seperate

DROP TABLE IF EXISTS STARNUMBER.DESTINATION_TYPE;

CREATE TABLE  STARNUMBER.DESTINATION_TYPE (
  DESTINATION_TYPE_id serial primary key,
  destination_type_name varchar(80),
  is_supported BOOLEAN DEFAULT false,
  create_time DATE,
  last_update_time DATE
);

COMMENT ON TABLE STARNUMBER.DESTINATION_TYPE IS 'This table tracks possible phone types that may be supported by Starnumber';

-- Now we insert some records.  This will only change as Starnumber adds support for new phone types.

INSERT INTO STARNUMBER.DESTINATION_TYPE (DESTINATION_TYPE_NAME, IS_SUPPORTED)
VALUES (
'URI',
TRUE
);

INSERT INTO STARNUMBER.DESTINATION_TYPE (DESTINATION_TYPE_NAME, IS_SUPPORTED)
VALUES (
'PSTN',
FALSE
);

INSERT INTO STARNUMBER.DESTINATION_TYPE (DESTINATION_TYPE_NAME, IS_SUPPORTED)
VALUES (
'Facebook',
FALSE
);



INSERT INTO STARNUMBER.DESTINATION_TYPE (DESTINATION_TYPE_NAME, IS_SUPPORTED)
VALUES (
'Sip',
TRUE
);

INSERT INTO STARNUMBER.DESTINATION_TYPE (DESTINATION_TYPE_NAME, IS_SUPPORTED)
VALUES (
'Skype',
FALSE
);

INSERT INTO STARNUMBER.DESTINATION_TYPE (DESTINATION_TYPE_NAME, IS_SUPPORTED)
VALUES (
'Google Voice',
FALSE
);

INSERT INTO STARNUMBER.DESTINATION_TYPE (DESTINATION_TYPE_NAME, IS_SUPPORTED)
VALUES (
'Starphone',
FALSE
);

commit;


SELECT COUNT(DESTINATION_TYPE_ID) FROM STARNUMBER.DESTINATION_TYPE;

SELECT * FROM STARNUMBER.DESTINATION_TYPE;

